---
# flavor
test_flavor: s3.medium.2

# Variables for testing of the hybrid environments
test_keypair_name: api_monitoring_test
test_security_group_name: test_sg
test_server_fqdn: test_scenario.bastion.host

# those hosts are used in the scenario30 to watch latencies
watch_hosts:
  - host: "https://console.otc.icsi.eumetsat.int"
    name: "console_eum"
  - host: "https://console.o13bb.otc.t-systems.com"
    name: "console_sbb"
  - host: "https://docs.o13bb.otc.t-systems.com"
    name: "docs_eum"
  - host: "https://docs.otc.icsi.eumetsat.int"
    name: "docs_sbb"
